### ISSUE TITLE
Networking With 4 or more players

### ISSUE THREAD

**Issue by Manleyb** [trystanwong/TeamProject#1]
How are you going to make networking work with 4 or more players at the same time? What if it is not someone's turn and that person wants to buy a card? What if on accident 2 players do a turn at the same time? How will networking be handles in these situations?

**Comment by KawikaSuzuki** [comment]
Regarding the implementation of 4 players in our game we found due to the extreme amount of coding we would have to do and keeping track of not only one player and one opponent but also maybe 3 A.Is and 1 player or even 4 network players, would cause many problems along the lines so we stuck with 2 players in the end. This made it so we could focus more on the gameplay of the game instead of getting the functionality to keep up with more than two players which was a better sacrifice in our opinion. Regarding the buy card action we made it so that you could only buy a card within the time of your turn within the round/gambit so if it was the opponents turn you are unable to buy a card. We also created checkers to ensure that when it is not a players turn within a round they are unable to perform moves that would possibly alter the state of the game in a way that would hinder the games normal performance.
