### ISSUE TITLE
Rules Of The Game

### ISSUE THREAD

**Issue by VincentTr** [trystanwong/TeamProject#5]
Is there a way for the user to access the rules of the game? Or does the game run through the rules along with the gameplay? If it runs along with the gameplay, then it might be tedious! Make sure to have legibility of the rules for the user to fully understand the game. Other than that, everything really looks detailed and awesome!

**Comment by KawikaSuzuki** [comment]
Regarding the rules of the game we have a link to a website where it states not only all the rules but almost everything regarding the game itself like a manual. Due to time and just how enormous the game is on its own explaining the rules would along the road lead to a very long tutorial of how to play the game which would take away more time for us creating a game for the audience to enjoy. I would say though this game can be very complicated and implementing a tutorial or screen with all the rules would indeed make the gameplay much easier but due to how extensive the game is adding it would as you said, become very tedious. Thank you for the compliment and feedback though it is greatly appreciated.
